# Generated by Django 3.1.4 on 2020-12-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFC_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(default='Seattle, WA', max_length=255),
        ),
    ]
